[package]
name = "rust_test"
version = "0.1.0"
authors = ["pwouik"]
edition = "2018"
resolver="2"

[dependencies]
profiling = "1.0.4"
noise = "0.7"
anyhow = "1.0"
image = "0.23"
winit = "0.25"
cgmath = "0.18"
env_logger = "0.8"
log = "0.4"
wgpu = "0.11"
futures = "0.3"
bytemuck = { version = "1.7", features = [ "derive" ] }
crossbeam-channel = "0.5.1"
egui = "0.14"
egui_wgpu_backend = "0.13"
egui_winit_platform = "0.10.0"
lz4_flex = "0.9"

[features]
default = ["profiling/profile-with-tracy"]

